server:
  port: 8082
  concurrent-sessions: 20

spring:
  application:
    name: api-fetch-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
