server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: aggregation-service
          uri: lb://aggregation-service
          predicates:
            - Path=/**
          filters:
            - name: CircuitBreaker
              args:
                name: aggregation-service
                fallbackuri: forward:/onDemandServiceFallback

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
